### ISSUE TITLE
For v1

### ISSUE THREAD

**Issue by fcollonval** [fcollonval/ipannotoryous#1]
This issue keeps track of things to do for v1:

- [x] Synchronization of annotations between Python/JS
- [x] Synchronization of annotations between multiple views
- [x] Support headless mode with template (probably synchronizing template as widget attribute to allow dynamic templating)
- [x] Support defining a default list of tag for the tag widget (https://recogito.github.io/guides/extending-the-editor/)
- [x] Support save annotation snippet (see https://github.com/recogito/annotorious/issues/76#issuecomment-763377159)
- [x] Add selection events
- [x] Add easy delete button (https://github.com/recogito/annotorious/issues/77)
- [x] Fix overflow style when the widget is inside box widgets
- [x] Add tests
- [x] Add good notebook documentation
- [x] Binder on JLab

**Comment by rsimon** [comment]
Just a heads up that the `applyTemplate` is no longer available. (I think I left in a backward-compatible workaround for now, but deprecated. Either way... my docs need updating.) The new way for updating annotations in headless is now "programmatic" rather than "declarative" (sort of). See the code snippet here:

https://github.com/recogito/annotorious/releases/tag/v2.2.0

(Let me know if the mechanism lacks functionality you need!)

**Comment by fcollonval** [comment]
Thanks for the comment - I think the proposal in the release note you mentioned should cover the use case.
